# Introducción a NumPy

### Introducción:
NumPy es una biblioteca fundamental en Python para computación numérica. Proporciona estructuras de datos eficientes para trabajar con matrices multidimensionales y funciones para realizar operaciones matemáticas en estas matrices de manera rápida y eficiente. En esta guía, aprenderemos a utilizar NumPy para tareas comunes de análisis de datos.

### 1. Instalación de NumPy: Normalmente este paso no es necesario!!
Asegúrate de tener NumPy instalado en tu entorno de Python:
```bash
pip install numpy
```

### 2. Importación de NumPy:
```python
import numpy as np
```



In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


### 3. Creación de Arrays Numéricos:
```python
# Crear un array de una dimensión
array_1d = np.array([1, 2, 3, 4, 5])

# Crear un array de dos dimensiones (matriz)
matriz_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```


In [4]:
#create a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

#create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]



### 4. Operaciones Básicas con Arrays:
```python
# Suma de arrays
suma = array_1d + array_1d

# Multiplicación de arrays
producto = array_1d * 2

# Producto punto (dot product) de dos arrays
dot_product = np.dot(array_1d, array_1d)
```


In [8]:
#operations on arrays
a = np.array([1, 2, 3, 4, 5])
print("Original Array:", a)

#scalar addition
print("Scalar addition", a + 2)

#scalar multiplication
print("Scalar multiplication", a * 2)

#element-wise addition
print("Array element wise addition", a + a)

#element-wise multiplication
print("Array element wise multiplication", a * a)

#dot product
print(np.dot(a, a))

Original Array: [1 2 3 4 5]
Scalar addition [3 4 5 6 7]
Scalar multiplication [ 2  4  6  8 10]
Array element wise addition [ 2  4  6  8 10]
Array element wise multiplication [ 1  4  9 16 25]
55



### 5. Funciones y Métodos de NumPy:
```python
# Calcular la media de un array
media = np.mean(array_1d)

# Calcular la desviación estándar de un array
desviacion_estandar = np.std(array_1d)

# Redimensionar un array
array_redimensionado = np.reshape(array_1d, (2, 3))
```


In [12]:
a = np.array([1, 2, 3, 4, 5])
print("Original Array:", a)

#mean
print("Mean:", np.mean(a))

#standard deviation
print("Standard Deviation:", np.std(a))

#variance
print("Variance:", np.var(a))

#min
print("Min:", np.min(a))

#max
print("Max:", np.max(a))

#sum
print("Sum:", np.sum(a))

#cumulative sum
print("Cumulative Sum:", np.cumsum(a))

#cumulative product
print("Cumulative Product:", np.cumprod(a))

#redimensioning
#reshape() function is used to give a new shape to an array without changing its data.
#reshape(array, newshape, order='C')
#newshape is the new shape you want to give to the array.
#example: reshape(8, 2) will give a new shape to the array as 8 rows and 2 columns.
#order is an optional argument which can have the following values:
#'C' − C-style row-major order.
#'F' − F-style column-major order.
#'A' − Fortran style column-major order.
#'K' − read the elements in the order they occur in memory, except for reversing the data when strides are negative.
a = np.reshape(a, (5, 1))
print(a)

Original Array: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Sum: 15
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]
[[1]
 [2]
 [3]
 [4]
 [5]]



### Ejemplos :

#### Ejemplo 1: Análisis de Datos Financieros
```python
# Calcular el rendimiento promedio diario de una cartera de acciones
rendimientos_diarios = np.array([0.01, -0.02, 0.03, 0.005, -0.015])
rendimiento_promedio_diario = np.mean(rendimientos_diarios)
print("Rendimiento Promedio Diario:", rendimiento_promedio_diario)
```


In [13]:
dailyReturns = np.array([0.01, -0.02, 0.03, 0.005, -0.15])
print("Daily Returns:", dailyReturns)
print("Mean:", np.mean(dailyReturns))
print("Standard Deviation:", np.std(dailyReturns))

Daily Returns: [ 0.01  -0.02   0.03   0.005 -0.15 ]
Mean: -0.025
Standard Deviation: 0.0644980619863884



#### Ejemplo 2: Procesamiento de Imágenes
```python
# Cargar una imagen como un array NumPy
from PIL import Image

imagen = Image.open('data/imagen.jpg')
array_imagen = np.array(imagen)

# Calcular la media de los valores de píxel en cada canal de color
media_canal_rojo = np.mean(array_imagen[:, :, 0])
media_canal_verde = np.mean(array_imagen[:, :, 1])
media_canal_azul = np.mean(array_imagen[:, :, 2])

print("Media Canal Rojo:", media_canal_rojo)
print("Media Canal Verde:", media_canal_verde)
print("Media Canal Azul:", media_canal_azul)
```

In [17]:
#Load an image using numpy
#To load an image using numpy, you need to install the PIL library.
pip install pillow
from PIL import Image

img = Image.open('image.jpg')
array = np.array(img)

SyntaxError: invalid syntax (3203557842.py, line 3)

# Definición y Uso de Funciones en Python

### Introducción:
Las funciones son bloques de código reutilizables que realizan una tarea específica. Son una parte fundamental de la programación en Python y permiten organizar y modularizar el código de manera efectiva. En esta guía, aprenderemos cómo definir, llamar y utilizar funciones en Python.

### Definición de Funciones:
En Python, una función se define utilizando la palabra clave `def`, seguida del nombre de la función y paréntesis que pueden contener los parámetros de entrada de la función. El cuerpo de la función se indenta debajo de la declaración `def`.



```python
def nombre_de_la_funcion(parametro1, parametro2):
    # Cuerpo de la función
    # Realizar operaciones
    resultado = parametro1 + parametro2
    return resultado
```



### Llamada a Funciones:
Para llamar a una función, simplemente escribimos el nombre de la función seguido de paréntesis que contienen los argumentos necesarios, si los hay.

```python
# Llamar a la función y almacenar el resultado en una variable
resultado = nombre_de_la_funcion(10, 20)
print(resultado)  # Imprime 30
```



### Parámetros de Función:
Las funciones pueden tener cero o más parámetros. Los parámetros son variables que se utilizan para pasar valores a la función cuando se llama. Estos valores se denominan argumentos.

```python
def saludar(nombre):
    print("¡Hola,", nombre, "!")
    
saludar("Juan")  # Imprime "¡Hola, Juan!"
```



### Valores de Retorno:
Las funciones pueden devolver un valor utilizando la palabra clave `return`. Esto permite que una función calcule un resultado y lo devuelva para ser utilizado en otra parte del programa.

```python
def sumar(a, b):
    return a + b

resultado = sumar(10, 5)
print(resultado)  # Imprime 15
```




### Funciones con Valores Predeterminados:
Los parámetros de una función pueden tener valores predeterminados, lo que significa que si no se proporciona un valor cuando se llama a la función, se utilizará el valor predeterminado.

```python
def saludar(nombre="Mundo"):
    print("¡Hola,", nombre, "!")
    
saludar()  # Imprime "¡Hola, Mundo!"
saludar("Juan")  # Imprime "¡Hola, Juan!"
```



### Funciones con Argumentos Variables:
Las funciones pueden tener un número variable de argumentos utilizando `*args` para parámetros posicionales y `**kwargs` para parámetros de palabras clave.

```python
def imprimir_argumentos(*args, **kwargs):
    for arg in args:
        print("Argumento:", arg)
    for clave, valor in kwargs.items():
        print("Argumento con palabra clave:", clave, "=", valor)

imprimir_argumentos(1, 2, 3, nombre="Juan", edad=30)
```



### Funciones Anidadas:
Una función puede contener otra función dentro de ella. Estas funciones se denominan funciones anidadas.

```python
def exterior():
    print("Función exterior")
    
    def interior():
        print("Función interior")
    
    interior()

exterior()
```

In [3]:
def exterior():
    print("Función exterior")
    
    def interior():
        print("Función interior")
    
    interior()

exterior()


Función exterior
Función interior
